// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bookmarks: typeof import('./../components/Bookmarks.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    GoTop: typeof import('./../components/GoTop.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Plum: typeof import('./../components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    Tabs: typeof import('./../components/Tabs.vue')['default']
  }
}

export {}
